### ISSUE TITLE
Dark mode in Firefox

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#212]
We should have default white background color and black text color to avoid being overwritten by browser styles. In the dark mode of Firefox, the background will be #000 by default et text will be white. So I would suggest to add these default styles directly on `html`:

```css
html {
  background: white;
  color: black;
}

```
